name: PROD Workflow

on:
 repository_dispatch:
   types: [prod_trigger]
   
   
   
jobs:
  build:

    env:
     SolutionName: ${{ github.event.client_payload.solutionname }}
     prodCS: ${{ secrets.PRODUCTION_CS }}
     testCS: ${{ secrets.TEST_CS }}

    runs-on: self-hosted

    steps:
    - name: 'clone this repo'
      uses: actions/checkout@v2-beta

    - name: 'Power ALM Export action Checkout'
      uses: actions/checkout@v2-beta
      with:
        repository: poweralm/export
        ref: refs/heads/master
        token: ${{ secrets.PP_ACTION_SEC }}
        path: .github/export

    - name: 'Power ALM Import action Checkout'
      uses: actions/checkout@v2-beta
      with:
        repository: poweralm/import
        ref: refs/heads/master
        token: ${{ secrets.PP_ACTION_SEC }}
        path: .github/import

       
    - name: 'Export the Power Solution from UAT Environment'
      uses: ./.github/export
      with:
        connectionString: '${{ env.testCS }}'
        solutionName: ${{env.SolutionName}}
        ExportSolutionOutputPath: 'exported_managed'
        packageType: 'Managed'
        
    - name: 'Import the solution to Prod Environment'
      uses: ./.github/import
      with:
        ConnectionString: '${{ env.prodCS }}'
        SolutionFile: 'exported_managed\${{env.SolutionName}}.zip'
    
       
